name: rule-benchmarks

on:
  pull_request:
  push:
    branches: [develop, per-rule-benchmarks-5]

jobs:
  setup_env:
    runs-on: ubuntu-latest
    name: Setup test environment
    steps:
    - name: Install pipenv
      shell: bash
      run: |
        pip3 install pipenv
    - name: Install pipenv dev dependencies
      shell: bash
      run: |
        pipenv install -d
 
