name: rule-benchmarks

on:
  pull_request:
  push:
    branches: [develop, per-rule-benchmarks-5]

jobs:
  setup_env:
    runs-on: ubuntu-latest
    name: Setup test environment
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
    - name: Install pipenv
      shell: bash
      run: |
        pip3 install pipenv
    - name: Install pipenv dev dependencies
      shell: bash
      run: |
        pipenv install -d
    - name: Get formatted date
      id: vars
      shell: bash
      run: |
        echo "::set-output name=today::$(printf -v date '%(%Y-%m-%d)')"
    - name: Run benchmarks
      shell: bash
      run: |
        pipenv run pytest --benchmark-only --benchmark-json=${{ steps.vars.outputs.today }}.json --benchmark-histogram=${{ steps.vars.outputs.today }}.svg
    - name: Upload JSON results
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.vars.outputs.today }}.json
        path: ${{ steps.vars.outputs.today }}.json
    - name: Upload historgram
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.vars.outputs.today }}.svg
        path: ${{ steps.vars.outputs.today }}.svg