name: rule-benchmarks

on: [commit]

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    name: Setup test environment
    steps:
    - name: Install pipenv
      shell: bash
      run: |
        pip3 install pipenv
    - name: Install pipenv dev dependencies
      shell: bash
      run: |
        pipenv install -d
      # cf. https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action
