name: rule-benchmarks

on:
  workflow_dispatch:
    inputs:
      fake:
        description: Not used
        default: ''
  schedule:
  - cron: 0 0 * * SUN

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    name: Setup test environment
    steps:
    - name: Install pipenv
      shell: bash
      run: |
        pip3 install pipenv
    - name: Install pipenv dev dependencies
      shell: bash
      run: |
        pipenv install -d
      # cf. https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action
    - name: Get formatted date
      id: vars
      shell: bash
      run: |-
        echo "::set-output name=today::$(printf -v date '%(%Y-%m-%d)')"
